### ISSUE TITLE
Feature Request: Permission Node

### ISSUE THREAD

**Issue by TylerS1066** [Pocketkid2/Fill#2]
Self explanatory, have a permission node to allow people to use the wands.  It's been abused multiple times where someone cheats in a wand from a creative world/area into a survival one and doesn't have perms for the fill command, but is able to abuse the wand.

**Comment by keough99** [comment]
good idea i agree i kinda know how to add it but i dont really know how i might do a test

**Comment by keough99** [comment]
well its kinda outa my range of what i can do i can only do a small one but unfortunatly its out of what i can do in programming

**Comment by cccm5** [comment]
#3

**Comment by Pocketkid2** [comment]
There's a permission node for the command. Should there also be one for using a wand?

**Comment by Pocketkid2** [comment]
Done
